<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>aruco_localizer</name>
  <version>0.0.1</version>
  <description>ROS 2 Aruco Localization and Map/Marker Publisher Package in C++</description>
  <maintainer email="user@todo.todo">User</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>rosidl_default_generators</buildtool_depend>

  <!-- Core & ROS 2 Messages -->
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>visualization_msgs</depend>

  <!-- TF2 Libraries -->
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>tf2_eigen</depend>

  <!-- Vision & Image Transport -->
  <depend>cv_bridge</depend>
  <depend>image_transport</depend>

  <!-- 3rd Party Libraries & Nav2 -->
  <depend>yaml-cpp</depend>
  <depend>opencv</depend>
  <depend>rclcpp_action</depend>
  <depend>std_srvs</depend>
  <depend>std_msgs</depend>
  <depend>nav2_msgs</depend>
  <exec_depend>nav2_regulated_pure_pursuit_controller</exec_depend>
  <exec_depend>nav2_common</exec_depend>
  <exec_depend>nav2_collision_monitor</exec_depend>
  <exec_depend>cleanup_perception</exec_depend>
  <exec_depend>robot_motion</exec_depend>

  <exec_depend>rosidl_default_runtime</exec_depend>
  <member_of_group>rosidl_interface_packages</member_of_group>

  <test_depend>ament_cmake_gtest</test_depend>
  <test_depend>ament_cmake_pytest</test_depend>
  <test_depend>nav2_bringup</test_depend>
  <test_depend>python3-yaml</test_depend>
  <test_depend>lifecycle_msgs</test_depend>
  <test_depend>rclpy</test_depend>
  <test_depend>python3-numpy</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
