<?xml version="1.0"?>
<package format="3">
  <name>project_bringup</name>
  <version>0.1.0</version>
  <description>Top-level launch package for the TurtleBot3 perception, navigation, and manipulation stack.</description>
  <maintainer email="user@todo.todo">user</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>nav2_common</exec_depend>
  <exec_depend>ros2bag</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>rosbag2_storage_default_plugins</exec_depend>
  <exec_depend>controller_manager</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>turtlebot3_manipulation_description</exec_depend>
  <test_depend>ament_cmake_pytest</test_depend>
  <test_depend>python3-yaml</test_depend>
  <test_depend>rclpy</test_depend>
  <test_depend>rosbag2_py</test_depend>
  <test_depend>std_msgs</test_depend>

  <exec_depend>aruco_localizer</exec_depend>
  <exec_depend>robot_motion</exec_depend>
  <exec_depend>python3-yaml</exec_depend>
  <exec_depend>cleanup_task_manager</exec_depend>
  <exec_depend>cleanup_interfaces</exec_depend>
  <exec_depend>cleanup_perception</exec_depend>
  <exec_depend>cleanup_planner</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>nav2_bringup</exec_depend>
  <exec_depend>pick_and_place</exec_depend>
  <exec_depend>realsense2_camera</exec_depend>
  <exec_depend>realsense_bringup</exec_depend>
  <exec_depend>segmentation</exec_depend>
  <exec_depend>turtlebot3_manipulation_bringup</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
